// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVQwBKGHOcxXrjBnLFgMl996PuxdLyClM',
    appId: '1:355241928291:web:56cf745514cbf37c9e7a56',
    messagingSenderId: '355241928291',
    projectId: 'produtos-b1932',
    authDomain: 'produtos-b1932.firebaseapp.com',
    storageBucket: 'produtos-b1932.appspot.com',
    measurementId: 'G-09V8JVTSHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlWp6m9eHVocbhf19CQKqh4dk0AFf5Pow',
    appId: '1:355241928291:android:3aabba79b7b74ea49e7a56',
    messagingSenderId: '355241928291',
    projectId: 'produtos-b1932',
    storageBucket: 'produtos-b1932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-JGD0wWtOlOgT8nvEDl0hgtTQtmYdUCA',
    appId: '1:355241928291:ios:62edad77ca6536299e7a56',
    messagingSenderId: '355241928291',
    projectId: 'produtos-b1932',
    storageBucket: 'produtos-b1932.appspot.com',
    iosClientId: '355241928291-g75jp2nr5244bqfjiifq6soql8sl9c0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
